services:
    anavaro.birthdaycontrol.acplistener:
        class: anavaro\birthdaycontrol\event\acplistener
        arguments:
            - @controller.helper
            - @config
        tags:
            - { name: event.listener }
    anavaro.birthdaycontrol.mainlistener:
        class: anavaro\birthdaycontrol\event\mainlistener
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }